'use client'
import {useState,useEffect} from 'react'
export default function Page(){
const [region,setRegion]=useState<any>(null)
const [auth,setAuth]=useState(false)
const [btc,setBtc]=useState(85435)
useEffect(()=>{fetch('https://api.coingecko.com/api/v3/simple/price?ids=bitcoin&vs_currencies=usd').then(r=>r.json()).then(d=>{if(d.bitcoin?.usd)setBtc(d.bitcoin.usd)}).catch(()=>{})},[])
if(!region){return <div style={{minHeight:'100vh',display:'grid',placeItems:'center',background:'#0a0a0b',color:'#fff',padding:20}}><div><h2>Pilih Mode</h2><button onClick={()=>{setRegion('ID');localStorage.setItem('v23-region','ID')}} style={{width:'100%',padding:16,marginBottom:10}}>INDONESIA</button><button onClick={()=>{setRegion('GLOBAL');localStorage.setItem('v23-region','GLOBAL')}} style={{width:'100%',padding:16}}>GLOBAL</button></div></div>}
if(!auth){return <div style={{minHeight:'100vh',display:'grid',placeItems:'center',background:'#0a0a0b',color:'#fff',padding:20}}><div><h2>Login</h2><button onClick={()=>{setAuth(true);localStorage.setItem('v23-auth','1')}} style={{width:'100%',padding:12,marginTop:10}}>Google</button><button onClick={()=>{setAuth(true);localStorage.setItem('v23-auth','1')}} style={{width:'100%',padding:12,marginTop:8}}>Facebook</button></div></div>}
return <div style={{maxWidth:440,margin:'0 auto',minHeight:'100vh',background:'#0a0a0b',color:'#fff',paddingBottom:60}}><div style={{padding:12,borderBottom:'1px solid #27272a'}}><b>Dompet V23.4 FIX - BTC ${btc} - {region}</b><div style={{marginTop:8,display:'flex',gap:4}}><button style={{padding:'6px 16px'}}>Dompet</button><button style={{padding:'6px 16px'}}>Crypto</button></div></div><div style={{padding:12}}><div style={{display:'flex',gap:8}}><div style={{flex:1,padding:12,background:'#0ea5e9',borderRadius:12}}>TABUNGAN Rp 12.472.000</div><div style={{flex:1,padding:12,background:'#10b981',borderRadius:12}}>TAB BARU Rp 2.5jt</div></div></div><div style={{padding:12}}><b>Bank - BCA BNI BRI GoPay OVO DANA + Custom Global</b></div><div style={{position:'fixed',bottom:0,left:'50%',transform:'translateX(-50%)',width:'100%',maxWidth:440,background:'#18181b',display:'flex',justifyContent:'space-around',padding:'10px 0'}}><span>Home</span><span>Wallet</span><span>Crypto</span><span>History</span><span>Profile</span></div></div>
}
